name: fisio_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc_pattern: ^3.0.0
  flutter_bloc: ^7.3.0
  rive: ^0.7.9
  google_fonts:
  firebase_auth: ^1.2.0
  firebase_storage: ^8.1.0
  cloud_firestore: ^2.2.0
  firebase_core: ^1.2.0
  flutter_card_swipper: ^0.4.0
  url_launcher: ^6.0.4
  google_mobile_ads: ^0.13.0
  provider: ^6.0.0
  flutter_modular: ^4.0.0+6
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.1
  rxdart: ^0.27.0
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  animations: ^2.0.1
  asuka: ^2.0.0-nullsafety.3
  bot_toast: ^4.0.1
  google_sign_in: ^5.1.1
  shared_preferences: ^2.0.8
  firebase_dynamic_links: ^2.0.10
  font_awesome_flutter: ^9.2.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true

  assets:
   - assets/anims/
   - assets/images/

